# Generated by Django 4.2.6 on 2023-11-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdorm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormpost',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='dormpost',
            name='address',
            field=models.TextField(default='Istanbul/Turkey', max_length=200),
        ),
        migrations.AddField(
            model_name='dormpost',
            name='phone_number',
            field=models.CharField(default='+90134234234234', max_length=200),
        ),
    ]
